name: "Restart Container"

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: ðŸ³ Restart
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Copy over files to deploy
      - name: Copy files
        run: |
          mkdir -p deploy
          cp package.json deploy
          cp docker-compose.yml deploy

      - name: Deploy to Linode
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "./deploy"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}a
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_WEB_DIR }}
          SCRIPT_AFTER: |
            set -euxo pipefail
            cd ${{ secrets.TARGET_API_DIR }}

            echo "NODE_ENV=production" > .env

            docker compose -f docker-compose.yml down -v
            docker compose -f docker-compose.yml up --build --force-recreate -d
